### ISSUE TITLE
Javadoc formatting tags in deprecation warning of OpenAPI spec

### ISSUE THREAD

**Issue by jeaf-anaptecs** [anaptecs/jeaf-generator#11]
## Description
Javadoc formatting tags in deprecation warning of OpenAPI spec

<br>

## Generated Source Code
```
# ch.voev.nova.services.nova.v15.common.NOVAResponse
    NOVAResponse:
      type: object
      additionalProperties: false
      description: |
        Class is a technical base class for all NOVA responses. Every NOVA REST Resource will return a single instance subclass of this class here. Only in case of technical problems REST resources will return a JSON problem.
        Deprecated: Type will be replaced with generic response type <code>Response</code>.<br/><br/>During the transition the REST response (JSON) will stay runtime backward compatible (no joined deployment between clients and server required).<br/><br/>However, when migrating your source code, then compile errors will pop up. (since: 1.5.0, removed with: PI 20)
      deprecated: true
```
